### PR TITLE
Gordon CLI

### PR DESCRIPTION
**Pull request by xoebus**
_I thought I'd start a long-running code review branch to track the progress of completing this feature and open the branch up to feedback before it's done._

This branch aims to create a CLI for interacting with Warden containers. It is a Go replacement of the original Warden CLI. However, whereas the original was a REPL this CLI will just allow one command per execution in order to keep it simple. Initially the output will be presented in a human-friendly format but by the end of the branch it should be possible to use the CLI within scripts to orchestrate the containers.

### CODE REVIEW

**Comment by xoebus** [comment]
I think that `Command.Run()` should return an error so that the correct exit code can be returned. The commands are getting a bit repetitive though and I'd like to find a cleaner way of writing them.

**Comment by xoebus** [comment]
Okay, that's `link` added.

I'm still not 100% sure how link is supposed to work (which, I'm sure, is quite reassuring given the 3 commits I just pushed). Whenever I kick off a job with spawn, wait for it to return a job ID, and then try and link to it it claims that there is no such job with the returned ID. If it pre-empt the returning of the ID and guess what it is going to be then I get some empty response.

I'm confused.

Link Command

**Comment by xoebus** [comment]
Here's one with me being as instant as possible:

Instant Link

**Comment by xoebus** [comment]
Okay, I put a sleep in and now everything is happy. Cool.

**Comment by vito** [comment]
Yep, the job ID is only valid as long as the script is running. You'll need a sleep in the script to properly test.

I've been doing something like `spawn --handle X --script 'sleep 10; echo hi out; echo hi err 1>&2; exit 42'` to test the 3 different things (stdout, stderr, exit status).

**Pull request closed without merging**
